"""Root-cause narrative generation for a failure cluster.

Three modes, same return shape (a plain string), so callers never need to
know which one ran:

- No API key set (the default): a deterministic, template-based summary.
  Zero cost, zero network calls, always available - this is what makes the
  rest of the pipeline usable with no API key at all.
- ``ANTHROPIC_API_KEY`` set: a short natural-language root-cause narrative
  generated by Claude from the cluster's signature, category, and a sample
  stack trace.
- ``OPENAI_API_KEY`` set: the same narrative, generated by an OpenAI chat
  model instead. Lets this tool run on whichever vendor a team already has
  a contract/key for, rather than locking in to one provider.

If both keys are set, ``ANTHROPIC_API_KEY`` wins unless ``LLM_PROVIDER`` is
set explicitly to ``"anthropic"`` or ``"openai"``.
"""

from __future__ import annotations

import os

from triage.models import Category, Cluster

_DEFAULT_MODEL = "claude-opus-5"
_DEFAULT_OPENAI_MODEL = "gpt-4o-mini"
_MAX_TOKENS = 400

_MODEL_ENV_VAR = "CLAUDE_MODEL"
_API_KEY_ENV_VAR = "ANTHROPIC_API_KEY"
_OPENAI_MODEL_ENV_VAR = "OPENAI_MODEL"
_OPENAI_API_KEY_ENV_VAR = "OPENAI_API_KEY"
_PROVIDER_ENV_VAR = "LLM_PROVIDER"

_SYSTEM_PROMPT = (
    "You are a senior SDET triaging automated test failures. Given a cluster "
    "of failures believed to share one root cause, write a concise (2-4 "
    "sentence) root-cause narrative: what likely broke, why these failures "
    "were grouped together, and one concrete next step for a human to "
    "investigate. Do not repeat the raw stack trace back verbatim."
)

_TEMPLATE_HINTS = {
    Category.FLAKY: "Likely environment/timing-related rather than a real product defect - "
    "consider adding explicit waits or a retry policy before assuming a regression.",
    Category.INFRA: "Likely an environment/connectivity problem outside the application under "
    "test - check that dependent services and network access were available during this run.",
    Category.REGRESSION: "No known flaky/infra signal matched - treat as a genuine candidate "
    "regression until a human rules it out.",
}


def narrate_cluster(
    cluster: Cluster,
    client: object | None = None,
    openai_client: object | None = None,
) -> str:
    """Return a short root-cause narrative for a cluster.

    ``client`` (an Anthropic-shaped client) and ``openai_client`` (an
    OpenAI-shaped client) are injection points for tests - callers who don't
    supply either get provider selection from environment variables, and
    ultimately fall back to a deterministic template when no key is
    configured, so this always returns something useful without ever
    requiring network access or an API key.
    """
    if client is not None:
        return _narrate_anthropic(cluster, client)
    if openai_client is not None:
        return _narrate_openai(cluster, openai_client)

    provider = _select_provider()
    if provider == "openai":
        return _narrate_openai(cluster)
    if provider == "anthropic":
        return _narrate_anthropic(cluster)
    return _template_narrative(cluster)


def _select_provider() -> str | None:
    """Pick which configured provider (if any) should generate the narrative.

    An explicit ``LLM_PROVIDER`` always wins. Otherwise, prefer Anthropic
    when both keys happen to be set, purely for backward-compatible
    behavior with existing deployments - either provider produces the same
    shape of output.
    """
    forced = os.environ.get(_PROVIDER_ENV_VAR)
    if forced in ("anthropic", "openai"):
        return forced
    if os.environ.get(_API_KEY_ENV_VAR):
        return "anthropic"
    if os.environ.get(_OPENAI_API_KEY_ENV_VAR):
        return "openai"
    return None


def _narrate_anthropic(cluster: Cluster, client: object | None = None) -> str:
    if client is None:
        api_key = os.environ.get(_API_KEY_ENV_VAR)
        if not api_key:
            return _template_narrative(cluster)

        import anthropic

        client = anthropic.Anthropic(api_key=api_key)

    model = os.environ.get(_MODEL_ENV_VAR, _DEFAULT_MODEL)
    prompt = _build_prompt(cluster)

    try:
        response = client.messages.create(
            model=model,
            max_tokens=_MAX_TOKENS,
            system=_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )
    except Exception:
        # Any API/network failure degrades to the offline template rather
        # than breaking the whole triage run over an LLM hiccup.
        return _template_narrative(cluster)

    for block in response.content:
        if getattr(block, "type", None) == "text":
            return block.text.strip()

    return _template_narrative(cluster)


def _narrate_openai(cluster: Cluster, client: object | None = None) -> str:
    if client is None:
        api_key = os.environ.get(_OPENAI_API_KEY_ENV_VAR)
        if not api_key:
            return _template_narrative(cluster)

        import openai

        client = openai.OpenAI(api_key=api_key)

    model = os.environ.get(_OPENAI_MODEL_ENV_VAR, _DEFAULT_OPENAI_MODEL)
    prompt = _build_prompt(cluster)

    try:
        response = client.chat.completions.create(
            model=model,
            max_tokens=_MAX_TOKENS,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
        )
    except Exception:
        # Same graceful degradation as the Anthropic path - a rate limit,
        # bad key, or network blip never takes down the whole triage run.
        return _template_narrative(cluster)

    choices = getattr(response, "choices", None) or []
    if choices:
        content = getattr(choices[0].message, "content", None)
        if content:
            return content.strip()

    return _template_narrative(cluster)


def _build_prompt(cluster: Cluster) -> str:
    representative = cluster.representative.record
    affected = ", ".join(m.record.full_name for m in cluster.members)
    return (
        f"Category: {cluster.category.value}\n"
        f"Cluster signature: {cluster.signature}\n"
        f"Affected tests ({cluster.size}): {affected}\n"
        f"Representative failure: {representative.full_name}\n"
        f"Message: {representative.message}\n"
        f"Stack trace (representative):\n{representative.stack_trace}"
    )


def _template_narrative(cluster: Cluster) -> str:
    representative = cluster.representative.record
    hint = _TEMPLATE_HINTS[cluster.category]
    plural = "test" if cluster.size == 1 else "tests"
    return (
        f"{cluster.size} {plural} failed with a matching {cluster.category.value} signature "
        f"(representative: {representative.full_name} - {representative.message}). {hint}"
    )
